#!/bin/bash
#$ -V
#$ -S /bin/bash
#$ -N FusorSV
#$ -cwd
#$ -o /u/flashscratch/h/hjzhou/6-5-18FusorSV449.$JOB_ID.out
#$ -j y
#$ -m bea
#$ -l h_data=64G,h_rt=24:00:00

# load python/2.7.2 from hoffman2, which have installed all the necessary modules.
. /u/local/Modules/default/init/modules.sh
module load python/2.7 

# HG19 seems not very compatible. Use HG37 instead. 

python ~/.local/bin/FusorSV.py \
-r $SCRATCH/reference/human_g1k_v37.fasta \
-i $SCRATCH/mysamples/ \
-f DEFAULT \
-o $SCRATCH/mysamples_64G_WG/ \
-M 0.5 \
-p 1 \
-L DEFAULT



