#!/bin/bash
#$ -V
#$ -S /bin/bash
#$ -N FusorSV
#$ -cwd
#$ -o /u/flashscratch/h/hjzhou/7-6-18FusorSV.mysamples.$JOB_ID.$TASK_ID.out
#$ -j y
#$ -m bea
#$ -l h_data=10G,h_rt=24:00:00
#$ -t 1-2:1


. /u/local/Modules/default/init/modules.sh
module load python/2.7 

python ~/.local/bin/FusorSV.py \
-r $SCRATCH/Homo_sapiens_assembly19.chr_rm.fasta \
-m $SCRATCH/Homo_sapiens_assembly19.mask.101.fasta.chr_rm.bed \
-i $SCRATCH/mysamples/batch$SGE_TASK_ID/ \
-f DEFAULT \
-o $SCRATCH/mysamples_result_masked/ \
-M 0.5 \
-p 1 \
--no_merge


#/u/project/zarlab/jhsul/bin/bam_to_fastq/bam_to_fastq_3
